apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: aqmrg
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: admin_token # This will be overridden by env in compose if needed, but provisioner usually needs a value
